### PR TITLE
install stylint local for the linter.

### PR DESCRIPTION
**Pull request by steveoh**
other [linters do this](https://github.com/AtomLinter/linter-jshint/blob/master/package.json#L13). Maybe it will help with refs #9?

### CODE REVIEW

**Comment by matthojo** [comment]
This was originally removed (https://github.com/AtomLinter/linter-stylint/commit/999f9c9b99cd2224de3f5f9b9138f0f31852f6ee) as Stylint contained an npm module which was incompatible with Atom builds. Do you know if this works in the new versions of Atom?

If no problem exists anymore I am happy to merge this in, but please could you update the default Stylint path https://github.com/AtomLinter/linter-stylint/blob/master/lib/init.coffee#L8 to point to the new Stylint module, like https://github.com/AtomLinter/linter-jshint/blob/master/lib/init.coffee#L6.

Side note: You can also update the Stylint path in your Atom settings, for you Windows install location. The default location for `linter-stylint` is for Unix machines.

**Comment by steveoh** [comment]
I do not know if this works in new versions of atom. I have never tested locally. So I'll give [these instructions](https://discuss.atom.io/t/load-developing-package/2554/4) a shot and see how it goes.

**Comment by steveoh** [comment]
This fixed #9 for me on windows. I can't get it to display errors on osx but it is not throwing an error and might just be my linter setup.

**Comment by steelbrain** [comment]
Be advised that this PR has some merge conflicts!

**Comment by matthojo** [comment]
@steelbrain I shall investigate this issue further at some point, currently the Stylint module itself causes errors when Atom rebuilds the package. So this issue can stay open as it is something I feel would benefit the project, but currently is a little out of our control.

**Pull request closed without merging**
